WITH SALES_INFO AS (
    SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
    GROUP BY YEAR, MONTH, USER_ID
)
SELECT YEAR, MONTH, GENDER, COUNT(SI.USER_ID) AS USERS
FROM SALES_INFO SI JOIN USER_INFO UI ON SI.USER_ID = UI.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3;